// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/components/spherical_harmonics.fbs".

#pragma once

#include "../datatypes/sh.hpp"
#include "../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace rerun::components {
    /// **Component**: A spherical harmonics up to degree 3.
    struct SphericalHarmonics {
        rerun::datatypes::Sh sh;

      public:
        SphericalHarmonics() = default;

        SphericalHarmonics(rerun::datatypes::Sh sh_) : sh(sh_) {}

        SphericalHarmonics& operator=(rerun::datatypes::Sh sh_) {
            sh = sh_;
            return *this;
        }

        SphericalHarmonics(std::array<float, 45> sh_) : sh(sh_) {}

        SphericalHarmonics& operator=(std::array<float, 45> sh_) {
            sh = sh_;
            return *this;
        }

        /// Cast to the underlying Sh datatype
        operator rerun::datatypes::Sh() const {
            return sh;
        }
    };
} // namespace rerun::components

namespace rerun {
    static_assert(sizeof(rerun::datatypes::Sh) == sizeof(components::SphericalHarmonics));

    /// \private
    template <>
    struct Loggable<components::SphericalHarmonics> {
        static constexpr std::string_view ComponentType = "rerun.components.SphericalHarmonics";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype() {
            return Loggable<rerun::datatypes::Sh>::arrow_datatype();
        }

        /// Serializes an array of `rerun::components::SphericalHarmonics` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const components::SphericalHarmonics* instances, size_t num_instances
        ) {
            if (num_instances == 0) {
                return Loggable<rerun::datatypes::Sh>::to_arrow(nullptr, 0);
            } else if (instances == nullptr) {
                return rerun::Error(
                    ErrorCode::UnexpectedNullArgument,
                    "Passed array instances is null when num_elements> 0."
                );
            } else {
                return Loggable<rerun::datatypes::Sh>::to_arrow(&instances->sh, num_instances);
            }
        }
    };
} // namespace rerun
