// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/rust/api.rs
// Based on "crates/store/re_types/definitions/rerun/archetypes/gaussians3d.fbs".

#![allow(unused_braces)]
#![allow(unused_imports)]
#![allow(unused_parens)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::map_flatten)]
#![allow(clippy::needless_question_mark)]
#![allow(clippy::new_without_default)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::too_many_lines)]

use ::re_types_core::SerializationResult;
use ::re_types_core::try_serialize_field;
use ::re_types_core::{ComponentBatch as _, SerializedComponentBatch};
use ::re_types_core::{ComponentDescriptor, ComponentType};
use ::re_types_core::{DeserializationError, DeserializationResult};

/// **Archetype**: 3D Gaussians.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Gaussians3D {
    /// The scales (standard deviation) along the three axes.
    pub scales: Option<SerializedComponentBatch>,

    /// The center position (mean) of the Gaussians.
    pub poss: Option<SerializedComponentBatch>,

    /// The rotation for the Gaussians via quaternion.
    pub rots: Option<SerializedComponentBatch>,

    /// The colors for the Gaussians.
    pub colors: Option<SerializedComponentBatch>,

    /// Optional spherical harmonics of the Gaussians, up to degree 3.
    pub sh: Option<SerializedComponentBatch>,

    /// Optional text labels for the Gaussians.
    pub labels: Option<SerializedComponentBatch>,

    /// Whether the text labels should be shown.
    ///
    /// If not set, labels will automatically appear when there is exactly one label for this entity
    /// or the number of instances on this entity is under a certain threshold.
    pub show_labels: Option<SerializedComponentBatch>,

    /// Optional class ID for the Gaussians.
    ///
    /// The class ID provides colors and labels if not specified explicitly.
    pub class_ids: Option<SerializedComponentBatch>,
}

impl Gaussians3D {
    /// Returns the [`ComponentDescriptor`] for [`Self::scales`].
    ///
    /// The corresponding component is [`crate::components::HalfSize3D`].
    #[inline]
    pub fn descriptor_scales() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:scales".into(),
            component_type: Some("rerun.components.HalfSize3D".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::poss`].
    ///
    /// The corresponding component is [`crate::components::PoseTranslation3D`].
    #[inline]
    pub fn descriptor_poss() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:poss".into(),
            component_type: Some("rerun.components.PoseTranslation3D".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::rots`].
    ///
    /// The corresponding component is [`crate::components::PoseRotationQuat`].
    #[inline]
    pub fn descriptor_rots() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:rots".into(),
            component_type: Some("rerun.components.PoseRotationQuat".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::colors`].
    ///
    /// The corresponding component is [`crate::components::Color`].
    #[inline]
    pub fn descriptor_colors() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:colors".into(),
            component_type: Some("rerun.components.Color".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::sh`].
    ///
    /// The corresponding component is [`crate::components::SphericalHarmonics`].
    #[inline]
    pub fn descriptor_sh() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:sh".into(),
            component_type: Some("rerun.components.SphericalHarmonics".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::labels`].
    ///
    /// The corresponding component is [`crate::components::Text`].
    #[inline]
    pub fn descriptor_labels() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:labels".into(),
            component_type: Some("rerun.components.Text".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::show_labels`].
    ///
    /// The corresponding component is [`crate::components::ShowLabels`].
    #[inline]
    pub fn descriptor_show_labels() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:show_labels".into(),
            component_type: Some("rerun.components.ShowLabels".into()),
        }
    }

    /// Returns the [`ComponentDescriptor`] for [`Self::class_ids`].
    ///
    /// The corresponding component is [`crate::components::ClassId`].
    #[inline]
    pub fn descriptor_class_ids() -> ComponentDescriptor {
        ComponentDescriptor {
            archetype: Some("rerun.archetypes.Gaussians3D".into()),
            component: "Gaussians3D:class_ids".into(),
            component_type: Some("rerun.components.ClassId".into()),
        }
    }
}

static REQUIRED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 4usize]> =
    std::sync::LazyLock::new(|| {
        [
            Gaussians3D::descriptor_scales(),
            Gaussians3D::descriptor_poss(),
            Gaussians3D::descriptor_rots(),
            Gaussians3D::descriptor_colors(),
        ]
    });

static RECOMMENDED_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 0usize]> =
    std::sync::LazyLock::new(|| []);

static OPTIONAL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 4usize]> =
    std::sync::LazyLock::new(|| {
        [
            Gaussians3D::descriptor_sh(),
            Gaussians3D::descriptor_labels(),
            Gaussians3D::descriptor_show_labels(),
            Gaussians3D::descriptor_class_ids(),
        ]
    });

static ALL_COMPONENTS: std::sync::LazyLock<[ComponentDescriptor; 8usize]> =
    std::sync::LazyLock::new(|| {
        [
            Gaussians3D::descriptor_scales(),
            Gaussians3D::descriptor_poss(),
            Gaussians3D::descriptor_rots(),
            Gaussians3D::descriptor_colors(),
            Gaussians3D::descriptor_sh(),
            Gaussians3D::descriptor_labels(),
            Gaussians3D::descriptor_show_labels(),
            Gaussians3D::descriptor_class_ids(),
        ]
    });

impl Gaussians3D {
    /// The total number of components in the archetype: 4 required, 0 recommended, 4 optional
    pub const NUM_COMPONENTS: usize = 8usize;
}

impl ::re_types_core::Archetype for Gaussians3D {
    #[inline]
    fn name() -> ::re_types_core::ArchetypeName {
        "rerun.archetypes.Gaussians3D".into()
    }

    #[inline]
    fn display_name() -> &'static str {
        "Gaussians 3D"
    }

    #[inline]
    fn required_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        REQUIRED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn recommended_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        RECOMMENDED_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn optional_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        OPTIONAL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn all_components() -> ::std::borrow::Cow<'static, [ComponentDescriptor]> {
        ALL_COMPONENTS.as_slice().into()
    }

    #[inline]
    fn from_arrow_components(
        arrow_data: impl IntoIterator<Item = (ComponentDescriptor, arrow::array::ArrayRef)>,
    ) -> DeserializationResult<Self> {
        re_tracing::profile_function!();
        use ::re_types_core::{Loggable as _, ResultExt as _};
        let arrays_by_descr: ::nohash_hasher::IntMap<_, _> = arrow_data.into_iter().collect();
        let scales = arrays_by_descr
            .get(&Self::descriptor_scales())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_scales()));
        let poss = arrays_by_descr
            .get(&Self::descriptor_poss())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_poss()));
        let rots = arrays_by_descr
            .get(&Self::descriptor_rots())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_rots()));
        let colors = arrays_by_descr
            .get(&Self::descriptor_colors())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_colors()));
        let sh = arrays_by_descr
            .get(&Self::descriptor_sh())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_sh()));
        let labels = arrays_by_descr
            .get(&Self::descriptor_labels())
            .map(|array| SerializedComponentBatch::new(array.clone(), Self::descriptor_labels()));
        let show_labels = arrays_by_descr
            .get(&Self::descriptor_show_labels())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_show_labels())
            });
        let class_ids = arrays_by_descr
            .get(&Self::descriptor_class_ids())
            .map(|array| {
                SerializedComponentBatch::new(array.clone(), Self::descriptor_class_ids())
            });
        Ok(Self {
            scales,
            poss,
            rots,
            colors,
            sh,
            labels,
            show_labels,
            class_ids,
        })
    }
}

impl ::re_types_core::AsComponents for Gaussians3D {
    #[inline]
    fn as_serialized_batches(&self) -> Vec<SerializedComponentBatch> {
        use ::re_types_core::Archetype as _;
        [
            self.scales.clone(),
            self.poss.clone(),
            self.rots.clone(),
            self.colors.clone(),
            self.sh.clone(),
            self.labels.clone(),
            self.show_labels.clone(),
            self.class_ids.clone(),
        ]
        .into_iter()
        .flatten()
        .collect()
    }
}

impl ::re_types_core::ArchetypeReflectionMarker for Gaussians3D {}

impl Gaussians3D {
    /// Create a new `Gaussians3D`.
    #[inline]
    pub fn new(
        scales: impl IntoIterator<Item = impl Into<crate::components::HalfSize3D>>,
        poss: impl IntoIterator<Item = impl Into<crate::components::PoseTranslation3D>>,
        rots: impl IntoIterator<Item = impl Into<crate::components::PoseRotationQuat>>,
        colors: impl IntoIterator<Item = impl Into<crate::components::Color>>,
    ) -> Self {
        Self {
            scales: try_serialize_field(Self::descriptor_scales(), scales),
            poss: try_serialize_field(Self::descriptor_poss(), poss),
            rots: try_serialize_field(Self::descriptor_rots(), rots),
            colors: try_serialize_field(Self::descriptor_colors(), colors),
            sh: None,
            labels: None,
            show_labels: None,
            class_ids: None,
        }
    }

    /// Update only some specific fields of a `Gaussians3D`.
    #[inline]
    pub fn update_fields() -> Self {
        Self::default()
    }

    /// Clear all the fields of a `Gaussians3D`.
    #[inline]
    pub fn clear_fields() -> Self {
        use ::re_types_core::Loggable as _;
        Self {
            scales: Some(SerializedComponentBatch::new(
                crate::components::HalfSize3D::arrow_empty(),
                Self::descriptor_scales(),
            )),
            poss: Some(SerializedComponentBatch::new(
                crate::components::PoseTranslation3D::arrow_empty(),
                Self::descriptor_poss(),
            )),
            rots: Some(SerializedComponentBatch::new(
                crate::components::PoseRotationQuat::arrow_empty(),
                Self::descriptor_rots(),
            )),
            colors: Some(SerializedComponentBatch::new(
                crate::components::Color::arrow_empty(),
                Self::descriptor_colors(),
            )),
            sh: Some(SerializedComponentBatch::new(
                crate::components::SphericalHarmonics::arrow_empty(),
                Self::descriptor_sh(),
            )),
            labels: Some(SerializedComponentBatch::new(
                crate::components::Text::arrow_empty(),
                Self::descriptor_labels(),
            )),
            show_labels: Some(SerializedComponentBatch::new(
                crate::components::ShowLabels::arrow_empty(),
                Self::descriptor_show_labels(),
            )),
            class_ids: Some(SerializedComponentBatch::new(
                crate::components::ClassId::arrow_empty(),
                Self::descriptor_class_ids(),
            )),
        }
    }

    /// Partitions the component data into multiple sub-batches.
    ///
    /// Specifically, this transforms the existing [`SerializedComponentBatch`]es data into [`SerializedComponentColumn`]s
    /// instead, via [`SerializedComponentBatch::partitioned`].
    ///
    /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
    ///
    /// The specified `lengths` must sum to the total length of the component batch.
    ///
    /// [`SerializedComponentColumn`]: [::re_types_core::SerializedComponentColumn]
    #[inline]
    pub fn columns<I>(
        self,
        _lengths: I,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>>
    where
        I: IntoIterator<Item = usize> + Clone,
    {
        let columns = [
            self.scales
                .map(|scales| scales.partitioned(_lengths.clone()))
                .transpose()?,
            self.poss
                .map(|poss| poss.partitioned(_lengths.clone()))
                .transpose()?,
            self.rots
                .map(|rots| rots.partitioned(_lengths.clone()))
                .transpose()?,
            self.colors
                .map(|colors| colors.partitioned(_lengths.clone()))
                .transpose()?,
            self.sh
                .map(|sh| sh.partitioned(_lengths.clone()))
                .transpose()?,
            self.labels
                .map(|labels| labels.partitioned(_lengths.clone()))
                .transpose()?,
            self.show_labels
                .map(|show_labels| show_labels.partitioned(_lengths.clone()))
                .transpose()?,
            self.class_ids
                .map(|class_ids| class_ids.partitioned(_lengths.clone()))
                .transpose()?,
        ];
        Ok(columns.into_iter().flatten())
    }

    /// Helper to partition the component data into unit-length sub-batches.
    ///
    /// This is semantically similar to calling [`Self::columns`] with `std::iter::take(1).repeat(n)`,
    /// where `n` is automatically guessed.
    #[inline]
    pub fn columns_of_unit_batches(
        self,
    ) -> SerializationResult<impl Iterator<Item = ::re_types_core::SerializedComponentColumn>> {
        let len_scales = self.scales.as_ref().map(|b| b.array.len());
        let len_poss = self.poss.as_ref().map(|b| b.array.len());
        let len_rots = self.rots.as_ref().map(|b| b.array.len());
        let len_colors = self.colors.as_ref().map(|b| b.array.len());
        let len_sh = self.sh.as_ref().map(|b| b.array.len());
        let len_labels = self.labels.as_ref().map(|b| b.array.len());
        let len_show_labels = self.show_labels.as_ref().map(|b| b.array.len());
        let len_class_ids = self.class_ids.as_ref().map(|b| b.array.len());
        let len = None
            .or(len_scales)
            .or(len_poss)
            .or(len_rots)
            .or(len_colors)
            .or(len_sh)
            .or(len_labels)
            .or(len_show_labels)
            .or(len_class_ids)
            .unwrap_or(0);
        self.columns(std::iter::repeat_n(1, len))
    }

    /// The scales (standard deviation) along the three axes.
    #[inline]
    pub fn with_scales(
        mut self,
        scales: impl IntoIterator<Item = impl Into<crate::components::HalfSize3D>>,
    ) -> Self {
        self.scales = try_serialize_field(Self::descriptor_scales(), scales);
        self
    }

    /// The center position (mean) of the Gaussians.
    #[inline]
    pub fn with_poss(
        mut self,
        poss: impl IntoIterator<Item = impl Into<crate::components::PoseTranslation3D>>,
    ) -> Self {
        self.poss = try_serialize_field(Self::descriptor_poss(), poss);
        self
    }

    /// The rotation for the Gaussians via quaternion.
    #[inline]
    pub fn with_rots(
        mut self,
        rots: impl IntoIterator<Item = impl Into<crate::components::PoseRotationQuat>>,
    ) -> Self {
        self.rots = try_serialize_field(Self::descriptor_rots(), rots);
        self
    }

    /// The colors for the Gaussians.
    #[inline]
    pub fn with_colors(
        mut self,
        colors: impl IntoIterator<Item = impl Into<crate::components::Color>>,
    ) -> Self {
        self.colors = try_serialize_field(Self::descriptor_colors(), colors);
        self
    }

    /// Optional spherical harmonics of the Gaussians, up to degree 3.
    #[inline]
    pub fn with_sh(
        mut self,
        sh: impl IntoIterator<Item = impl Into<crate::components::SphericalHarmonics>>,
    ) -> Self {
        self.sh = try_serialize_field(Self::descriptor_sh(), sh);
        self
    }

    /// Optional text labels for the Gaussians.
    #[inline]
    pub fn with_labels(
        mut self,
        labels: impl IntoIterator<Item = impl Into<crate::components::Text>>,
    ) -> Self {
        self.labels = try_serialize_field(Self::descriptor_labels(), labels);
        self
    }

    /// Whether the text labels should be shown.
    ///
    /// If not set, labels will automatically appear when there is exactly one label for this entity
    /// or the number of instances on this entity is under a certain threshold.
    #[inline]
    pub fn with_show_labels(
        mut self,
        show_labels: impl Into<crate::components::ShowLabels>,
    ) -> Self {
        self.show_labels = try_serialize_field(Self::descriptor_show_labels(), [show_labels]);
        self
    }

    /// This method makes it possible to pack multiple [`crate::components::ShowLabels`] in a single component batch.
    ///
    /// This only makes sense when used in conjunction with [`Self::columns`]. [`Self::with_show_labels`] should
    /// be used when logging a single row's worth of data.
    #[inline]
    pub fn with_many_show_labels(
        mut self,
        show_labels: impl IntoIterator<Item = impl Into<crate::components::ShowLabels>>,
    ) -> Self {
        self.show_labels = try_serialize_field(Self::descriptor_show_labels(), show_labels);
        self
    }

    /// Optional class ID for the Gaussians.
    ///
    /// The class ID provides colors and labels if not specified explicitly.
    #[inline]
    pub fn with_class_ids(
        mut self,
        class_ids: impl IntoIterator<Item = impl Into<crate::components::ClassId>>,
    ) -> Self {
        self.class_ids = try_serialize_field(Self::descriptor_class_ids(), class_ids);
        self
    }
}

impl ::re_byte_size::SizeBytes for Gaussians3D {
    #[inline]
    fn heap_size_bytes(&self) -> u64 {
        self.scales.heap_size_bytes()
            + self.poss.heap_size_bytes()
            + self.rots.heap_size_bytes()
            + self.colors.heap_size_bytes()
            + self.sh.heap_size_bytes()
            + self.labels.heap_size_bytes()
            + self.show_labels.heap_size_bytes()
            + self.class_ids.heap_size_bytes()
    }
}
