// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/archetypes/gaussians3d.fbs".

#pragma once

#include "../collection.hpp"
#include "../component_batch.hpp"
#include "../component_column.hpp"
#include "../components/class_id.hpp"
#include "../components/color.hpp"
#include "../components/half_size3d.hpp"
#include "../components/pose_rotation_quat.hpp"
#include "../components/pose_translation3d.hpp"
#include "../components/show_labels.hpp"
#include "../components/spherical_harmonics.hpp"
#include "../components/text.hpp"
#include "../result.hpp"

#include <cstdint>
#include <optional>
#include <utility>
#include <vector>

namespace rerun::archetypes {
    /// **Archetype**: 3D Gaussians.
    struct Gaussians3D {
        /// The scales (standard deviation) along the three axes.
        std::optional<ComponentBatch> scales;

        /// The center position (mean) of the Gaussians.
        std::optional<ComponentBatch> poss;

        /// The rotation for the Gaussians via quaternion.
        std::optional<ComponentBatch> rots;

        /// The colors for the Gaussians.
        std::optional<ComponentBatch> colors;

        /// Optional spherical harmonics of the Gaussians, up to degree 3.
        std::optional<ComponentBatch> sh;

        /// Optional text labels for the Gaussians.
        std::optional<ComponentBatch> labels;

        /// Whether the text labels should be shown.
        ///
        /// If not set, labels will automatically appear when there is exactly one label for this entity
        /// or the number of instances on this entity is under a certain threshold.
        std::optional<ComponentBatch> show_labels;

        /// Optional class ID for the Gaussians.
        ///
        /// The class ID provides colors and labels if not specified explicitly.
        std::optional<ComponentBatch> class_ids;

      public:
        /// The name of the archetype as used in `ComponentDescriptor`s.
        static constexpr const char ArchetypeName[] = "rerun.archetypes.Gaussians3D";

        /// `ComponentDescriptor` for the `scales` field.
        static constexpr auto Descriptor_scales = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:scales",
            Loggable<rerun::components::HalfSize3D>::ComponentType
        );
        /// `ComponentDescriptor` for the `poss` field.
        static constexpr auto Descriptor_poss = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:poss",
            Loggable<rerun::components::PoseTranslation3D>::ComponentType
        );
        /// `ComponentDescriptor` for the `rots` field.
        static constexpr auto Descriptor_rots = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:rots",
            Loggable<rerun::components::PoseRotationQuat>::ComponentType
        );
        /// `ComponentDescriptor` for the `colors` field.
        static constexpr auto Descriptor_colors = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:colors", Loggable<rerun::components::Color>::ComponentType
        );
        /// `ComponentDescriptor` for the `sh` field.
        static constexpr auto Descriptor_sh = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:sh",
            Loggable<rerun::components::SphericalHarmonics>::ComponentType
        );
        /// `ComponentDescriptor` for the `labels` field.
        static constexpr auto Descriptor_labels = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:labels", Loggable<rerun::components::Text>::ComponentType
        );
        /// `ComponentDescriptor` for the `show_labels` field.
        static constexpr auto Descriptor_show_labels = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:show_labels",
            Loggable<rerun::components::ShowLabels>::ComponentType
        );
        /// `ComponentDescriptor` for the `class_ids` field.
        static constexpr auto Descriptor_class_ids = ComponentDescriptor(
            ArchetypeName, "Gaussians3D:class_ids",
            Loggable<rerun::components::ClassId>::ComponentType
        );

      public:
        Gaussians3D() = default;
        Gaussians3D(Gaussians3D&& other) = default;
        Gaussians3D(const Gaussians3D& other) = default;
        Gaussians3D& operator=(const Gaussians3D& other) = default;
        Gaussians3D& operator=(Gaussians3D&& other) = default;

        /// Update only some specific fields of a `Gaussians3D`.
        static Gaussians3D update_fields() {
            return Gaussians3D();
        }

        /// Clear all the fields of a `Gaussians3D`.
        static Gaussians3D clear_fields();

        /// The scales (standard deviation) along the three axes.
        Gaussians3D with_scales(const Collection<rerun::components::HalfSize3D>& _scales) && {
            scales = ComponentBatch::from_loggable(_scales, Descriptor_scales).value_or_throw();
            return std::move(*this);
        }

        /// The center position (mean) of the Gaussians.
        Gaussians3D with_poss(const Collection<rerun::components::PoseTranslation3D>& _poss) && {
            poss = ComponentBatch::from_loggable(_poss, Descriptor_poss).value_or_throw();
            return std::move(*this);
        }

        /// The rotation for the Gaussians via quaternion.
        Gaussians3D with_rots(const Collection<rerun::components::PoseRotationQuat>& _rots) && {
            rots = ComponentBatch::from_loggable(_rots, Descriptor_rots).value_or_throw();
            return std::move(*this);
        }

        /// The colors for the Gaussians.
        Gaussians3D with_colors(const Collection<rerun::components::Color>& _colors) && {
            colors = ComponentBatch::from_loggable(_colors, Descriptor_colors).value_or_throw();
            return std::move(*this);
        }

        /// Optional spherical harmonics of the Gaussians, up to degree 3.
        Gaussians3D with_sh(const Collection<rerun::components::SphericalHarmonics>& _sh) && {
            sh = ComponentBatch::from_loggable(_sh, Descriptor_sh).value_or_throw();
            return std::move(*this);
        }

        /// Optional text labels for the Gaussians.
        Gaussians3D with_labels(const Collection<rerun::components::Text>& _labels) && {
            labels = ComponentBatch::from_loggable(_labels, Descriptor_labels).value_or_throw();
            return std::move(*this);
        }

        /// Whether the text labels should be shown.
        ///
        /// If not set, labels will automatically appear when there is exactly one label for this entity
        /// or the number of instances on this entity is under a certain threshold.
        Gaussians3D with_show_labels(const rerun::components::ShowLabels& _show_labels) && {
            show_labels = ComponentBatch::from_loggable(_show_labels, Descriptor_show_labels)
                              .value_or_throw();
            return std::move(*this);
        }

        /// This method makes it possible to pack multiple `show_labels` in a single component batch.
        ///
        /// This only makes sense when used in conjunction with `columns`. `with_show_labels` should
        /// be used when logging a single row's worth of data.
        Gaussians3D with_many_show_labels(
            const Collection<rerun::components::ShowLabels>& _show_labels
        ) && {
            show_labels = ComponentBatch::from_loggable(_show_labels, Descriptor_show_labels)
                              .value_or_throw();
            return std::move(*this);
        }

        /// Optional class ID for the Gaussians.
        ///
        /// The class ID provides colors and labels if not specified explicitly.
        Gaussians3D with_class_ids(const Collection<rerun::components::ClassId>& _class_ids) && {
            class_ids =
                ComponentBatch::from_loggable(_class_ids, Descriptor_class_ids).value_or_throw();
            return std::move(*this);
        }

        /// Partitions the component data into multiple sub-batches.
        ///
        /// Specifically, this transforms the existing `ComponentBatch` data into `ComponentColumn`s
        /// instead, via `ComponentBatch::partitioned`.
        ///
        /// This makes it possible to use `RecordingStream::send_columns` to send columnar data directly into Rerun.
        ///
        /// The specified `lengths` must sum to the total length of the component batch.
        Collection<ComponentColumn> columns(const Collection<uint32_t>& lengths_);

        /// Partitions the component data into unit-length sub-batches.
        ///
        /// This is semantically similar to calling `columns` with `std::vector<uint32_t>(n, 1)`,
        /// where `n` is automatically guessed.
        Collection<ComponentColumn> columns();
    };

} // namespace rerun::archetypes

namespace rerun {
    /// \private
    template <typename T>
    struct AsComponents;

    /// \private
    template <>
    struct AsComponents<archetypes::Gaussians3D> {
        /// Serialize all set component batches.
        static Result<Collection<ComponentBatch>> as_batches(
            const archetypes::Gaussians3D& archetype
        );
    };
} // namespace rerun
