// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/archetypes/gaussians3d.fbs".

#include "gaussians3d.hpp"

#include "../collection_adapter_builtins.hpp"

namespace rerun::archetypes {
    Gaussians3D Gaussians3D::clear_fields() {
        auto archetype = Gaussians3D();
        archetype.scales = ComponentBatch::empty<rerun::components::HalfSize3D>(Descriptor_scales)
                               .value_or_throw();
        archetype.poss =
            ComponentBatch::empty<rerun::components::PoseTranslation3D>(Descriptor_poss)
                .value_or_throw();
        archetype.rots = ComponentBatch::empty<rerun::components::PoseRotationQuat>(Descriptor_rots)
                             .value_or_throw();
        archetype.colors =
            ComponentBatch::empty<rerun::components::Color>(Descriptor_colors).value_or_throw();
        archetype.sh = ComponentBatch::empty<rerun::components::SphericalHarmonics>(Descriptor_sh)
                           .value_or_throw();
        archetype.labels =
            ComponentBatch::empty<rerun::components::Text>(Descriptor_labels).value_or_throw();
        archetype.show_labels =
            ComponentBatch::empty<rerun::components::ShowLabels>(Descriptor_show_labels)
                .value_or_throw();
        archetype.class_ids =
            ComponentBatch::empty<rerun::components::ClassId>(Descriptor_class_ids)
                .value_or_throw();
        return archetype;
    }

    Collection<ComponentColumn> Gaussians3D::columns(const Collection<uint32_t>& lengths_) {
        std::vector<ComponentColumn> columns;
        columns.reserve(8);
        if (scales.has_value()) {
            columns.push_back(scales.value().partitioned(lengths_).value_or_throw());
        }
        if (poss.has_value()) {
            columns.push_back(poss.value().partitioned(lengths_).value_or_throw());
        }
        if (rots.has_value()) {
            columns.push_back(rots.value().partitioned(lengths_).value_or_throw());
        }
        if (colors.has_value()) {
            columns.push_back(colors.value().partitioned(lengths_).value_or_throw());
        }
        if (sh.has_value()) {
            columns.push_back(sh.value().partitioned(lengths_).value_or_throw());
        }
        if (labels.has_value()) {
            columns.push_back(labels.value().partitioned(lengths_).value_or_throw());
        }
        if (show_labels.has_value()) {
            columns.push_back(show_labels.value().partitioned(lengths_).value_or_throw());
        }
        if (class_ids.has_value()) {
            columns.push_back(class_ids.value().partitioned(lengths_).value_or_throw());
        }
        return columns;
    }

    Collection<ComponentColumn> Gaussians3D::columns() {
        if (scales.has_value()) {
            return columns(std::vector<uint32_t>(scales.value().length(), 1));
        }
        if (poss.has_value()) {
            return columns(std::vector<uint32_t>(poss.value().length(), 1));
        }
        if (rots.has_value()) {
            return columns(std::vector<uint32_t>(rots.value().length(), 1));
        }
        if (colors.has_value()) {
            return columns(std::vector<uint32_t>(colors.value().length(), 1));
        }
        if (sh.has_value()) {
            return columns(std::vector<uint32_t>(sh.value().length(), 1));
        }
        if (labels.has_value()) {
            return columns(std::vector<uint32_t>(labels.value().length(), 1));
        }
        if (show_labels.has_value()) {
            return columns(std::vector<uint32_t>(show_labels.value().length(), 1));
        }
        if (class_ids.has_value()) {
            return columns(std::vector<uint32_t>(class_ids.value().length(), 1));
        }
        return Collection<ComponentColumn>();
    }
} // namespace rerun::archetypes

namespace rerun {

    Result<Collection<ComponentBatch>> AsComponents<archetypes::Gaussians3D>::as_batches(
        const archetypes::Gaussians3D& archetype
    ) {
        using namespace archetypes;
        std::vector<ComponentBatch> cells;
        cells.reserve(8);

        if (archetype.scales.has_value()) {
            cells.push_back(archetype.scales.value());
        }
        if (archetype.poss.has_value()) {
            cells.push_back(archetype.poss.value());
        }
        if (archetype.rots.has_value()) {
            cells.push_back(archetype.rots.value());
        }
        if (archetype.colors.has_value()) {
            cells.push_back(archetype.colors.value());
        }
        if (archetype.sh.has_value()) {
            cells.push_back(archetype.sh.value());
        }
        if (archetype.labels.has_value()) {
            cells.push_back(archetype.labels.value());
        }
        if (archetype.show_labels.has_value()) {
            cells.push_back(archetype.show_labels.value());
        }
        if (archetype.class_ids.has_value()) {
            cells.push_back(archetype.class_ids.value());
        }

        return rerun::take_ownership(std::move(cells));
    }
} // namespace rerun
