# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_types/definitions/rerun/components/spherical_harmonics.fbs".

# You can extend this class by creating a "SphericalHarmonicsExt" class in "spherical_harmonics_ext.py".

from __future__ import annotations

from .. import datatypes
from .._baseclasses import (
    ComponentBatchMixin,
    ComponentMixin,
)

__all__ = ["SphericalHarmonics", "SphericalHarmonicsBatch"]


class SphericalHarmonics(datatypes.Sh, ComponentMixin):
    """**Component**: A spherical harmonics up to degree 3."""

    _BATCH_TYPE = None
    # You can define your own __init__ function as a member of SphericalHarmonicsExt in spherical_harmonics_ext.py

    # Note: there are no fields here because SphericalHarmonics delegates to datatypes.Sh


class SphericalHarmonicsBatch(datatypes.ShBatch, ComponentBatchMixin):
    _COMPONENT_TYPE: str = "rerun.components.SphericalHarmonics"


# This is patched in late to avoid circular dependencies.
SphericalHarmonics._BATCH_TYPE = SphericalHarmonicsBatch  # type: ignore[assignment]
