# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_types/definitions/rerun/datatypes/sh.fbs".

# You can extend this class by creating a "ShExt" class in "sh_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Union

import numpy as np
import numpy.typing as npt
import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)
from .._converters import (
    to_np_float32,
)
from .._numpy_compatibility import asarray

__all__ = ["Sh", "ShArrayLike", "ShBatch", "ShLike"]


@define(init=False)
class Sh:
    """
    **Datatype**: A spherical harmonics.

    This does not include 0-th degree. It supports up to 3 degrees.
    """

    def __init__(self: Any, sh: ShLike) -> None:
        """Create a new instance of the Sh datatype."""

        # You can define your own __init__ function as a member of ShExt in sh_ext.py
        self.__attrs_init__(sh=sh)

    sh: npt.NDArray[np.float32] = field(converter=to_np_float32)

    def __array__(self, dtype: npt.DTypeLike = None, copy: bool | None = None) -> npt.NDArray[Any]:
        # You can define your own __array__ function as a member of ShExt in sh_ext.py
        return asarray(self.sh, dtype=dtype, copy=copy)

    def __len__(self) -> int:
        # You can define your own __len__ function as a member of ShExt in sh_ext.py
        return len(self.sh)


if TYPE_CHECKING:
    ShLike = Union[Sh, npt.NDArray[Any], npt.ArrayLike, Sequence[float]]
else:
    ShLike = Any

ShArrayLike = Union[Sh, Sequence[ShLike], npt.NDArray[Any], npt.ArrayLike, Sequence[Sequence[float]], Sequence[float]]


class ShBatch(BaseBatch[ShArrayLike]):
    _ARROW_DATATYPE = pa.list_(pa.field("item", pa.float32(), nullable=False, metadata={}), 45)

    @staticmethod
    def _native_to_pa_array(data: ShArrayLike, data_type: pa.DataType) -> pa.Array:
        raise NotImplementedError(
            "Arrow serialization of Sh not implemented: We lack codegen for arrow-serialization of general structs"
        )  # You need to implement native_to_pa_array_override in sh_ext.py
