# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_types/definitions/rerun/archetypes/gaussians3d.fbs".

# You can extend this class by creating a "Gaussians3DExt" class in "gaussians3d_ext.py".

from __future__ import annotations

from typing import Any

import numpy as np
import pyarrow as pa
from attrs import define, field

from .. import components, datatypes
from .._baseclasses import (
    Archetype,
    ComponentColumnList,
)
from ..error_utils import catch_and_log_exceptions

__all__ = ["Gaussians3D"]


@define(str=False, repr=False, init=False)
class Gaussians3D(Archetype):
    """**Archetype**: 3D Gaussians."""

    def __init__(
        self: Any,
        scales: datatypes.Vec3DArrayLike,
        poss: datatypes.Vec3DArrayLike,
        rots: datatypes.QuaternionArrayLike,
        colors: datatypes.Rgba32ArrayLike,
        *,
        sh: datatypes.ShArrayLike | None = None,
        labels: datatypes.Utf8ArrayLike | None = None,
        show_labels: datatypes.BoolLike | None = None,
        class_ids: datatypes.ClassIdArrayLike | None = None,
    ) -> None:
        """
        Create a new instance of the Gaussians3D archetype.

        Parameters
        ----------
        scales:
            The scales (standard deviation) along the three axes.
        poss:
            The center position (mean) of the Gaussians.
        rots:
            The rotation for the Gaussians via quaternion.
        colors:
            The colors for the Gaussians.
        sh:
            Optional spherical harmonics of the Gaussians, up to degree 3.
        labels:
            Optional text labels for the Gaussians.
        show_labels:
            Whether the text labels should be shown.

            If not set, labels will automatically appear when there is exactly one label for this entity
            or the number of instances on this entity is under a certain threshold.
        class_ids:
            Optional class ID for the Gaussians.

            The class ID provides colors and labels if not specified explicitly.

        """

        # You can define your own __init__ function as a member of Gaussians3DExt in gaussians3d_ext.py
        with catch_and_log_exceptions(context=self.__class__.__name__):
            self.__attrs_init__(
                scales=scales,
                poss=poss,
                rots=rots,
                colors=colors,
                sh=sh,
                labels=labels,
                show_labels=show_labels,
                class_ids=class_ids,
            )
            return
        self.__attrs_clear__()

    def __attrs_clear__(self) -> None:
        """Convenience method for calling `__attrs_init__` with all `None`s."""
        self.__attrs_init__(
            scales=None,
            poss=None,
            rots=None,
            colors=None,
            sh=None,
            labels=None,
            show_labels=None,
            class_ids=None,
        )

    @classmethod
    def _clear(cls) -> Gaussians3D:
        """Produce an empty Gaussians3D, bypassing `__init__`."""
        inst = cls.__new__(cls)
        inst.__attrs_clear__()
        return inst

    @classmethod
    def from_fields(
        cls,
        *,
        clear_unset: bool = False,
        scales: datatypes.Vec3DArrayLike | None = None,
        poss: datatypes.Vec3DArrayLike | None = None,
        rots: datatypes.QuaternionArrayLike | None = None,
        colors: datatypes.Rgba32ArrayLike | None = None,
        sh: datatypes.ShArrayLike | None = None,
        labels: datatypes.Utf8ArrayLike | None = None,
        show_labels: datatypes.BoolLike | None = None,
        class_ids: datatypes.ClassIdArrayLike | None = None,
    ) -> Gaussians3D:
        """
        Update only some specific fields of a `Gaussians3D`.

        Parameters
        ----------
        clear_unset:
            If true, all unspecified fields will be explicitly cleared.
        scales:
            The scales (standard deviation) along the three axes.
        poss:
            The center position (mean) of the Gaussians.
        rots:
            The rotation for the Gaussians via quaternion.
        colors:
            The colors for the Gaussians.
        sh:
            Optional spherical harmonics of the Gaussians, up to degree 3.
        labels:
            Optional text labels for the Gaussians.
        show_labels:
            Whether the text labels should be shown.

            If not set, labels will automatically appear when there is exactly one label for this entity
            or the number of instances on this entity is under a certain threshold.
        class_ids:
            Optional class ID for the Gaussians.

            The class ID provides colors and labels if not specified explicitly.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            kwargs = {
                "scales": scales,
                "poss": poss,
                "rots": rots,
                "colors": colors,
                "sh": sh,
                "labels": labels,
                "show_labels": show_labels,
                "class_ids": class_ids,
            }

            if clear_unset:
                kwargs = {k: v if v is not None else [] for k, v in kwargs.items()}  # type: ignore[misc]

            inst.__attrs_init__(**kwargs)
            return inst

        inst.__attrs_clear__()
        return inst

    @classmethod
    def cleared(cls) -> Gaussians3D:
        """Clear all the fields of a `Gaussians3D`."""
        return cls.from_fields(clear_unset=True)

    @classmethod
    def columns(
        cls,
        *,
        scales: datatypes.Vec3DArrayLike | None = None,
        poss: datatypes.Vec3DArrayLike | None = None,
        rots: datatypes.QuaternionArrayLike | None = None,
        colors: datatypes.Rgba32ArrayLike | None = None,
        sh: datatypes.ShArrayLike | None = None,
        labels: datatypes.Utf8ArrayLike | None = None,
        show_labels: datatypes.BoolArrayLike | None = None,
        class_ids: datatypes.ClassIdArrayLike | None = None,
    ) -> ComponentColumnList:
        """
        Construct a new column-oriented component bundle.

        This makes it possible to use `rr.send_columns` to send columnar data directly into Rerun.

        The returned columns will be partitioned into unit-length sub-batches by default.
        Use `ComponentColumnList.partition` to repartition the data as needed.

        Parameters
        ----------
        scales:
            The scales (standard deviation) along the three axes.
        poss:
            The center position (mean) of the Gaussians.
        rots:
            The rotation for the Gaussians via quaternion.
        colors:
            The colors for the Gaussians.
        sh:
            Optional spherical harmonics of the Gaussians, up to degree 3.
        labels:
            Optional text labels for the Gaussians.
        show_labels:
            Whether the text labels should be shown.

            If not set, labels will automatically appear when there is exactly one label for this entity
            or the number of instances on this entity is under a certain threshold.
        class_ids:
            Optional class ID for the Gaussians.

            The class ID provides colors and labels if not specified explicitly.

        """

        inst = cls.__new__(cls)
        with catch_and_log_exceptions(context=cls.__name__):
            inst.__attrs_init__(
                scales=scales,
                poss=poss,
                rots=rots,
                colors=colors,
                sh=sh,
                labels=labels,
                show_labels=show_labels,
                class_ids=class_ids,
            )

        batches = inst.as_component_batches()
        if len(batches) == 0:
            return ComponentColumnList([])

        kwargs = {
            "Gaussians3D:scales": scales,
            "Gaussians3D:poss": poss,
            "Gaussians3D:rots": rots,
            "Gaussians3D:colors": colors,
            "Gaussians3D:sh": sh,
            "Gaussians3D:labels": labels,
            "Gaussians3D:show_labels": show_labels,
            "Gaussians3D:class_ids": class_ids,
        }
        columns = []

        for batch in batches:
            arrow_array = batch.as_arrow_array()

            # For primitive arrays and fixed size list arrays, we infer partition size from the input shape.
            if pa.types.is_primitive(arrow_array.type) or pa.types.is_fixed_size_list(arrow_array.type):
                param = kwargs[batch.component_descriptor().component]  # type: ignore[index]
                shape = np.shape(param)  # type: ignore[arg-type]
                elem_flat_len = int(np.prod(shape[1:])) if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                if pa.types.is_fixed_size_list(arrow_array.type) and arrow_array.type.list_size == elem_flat_len:
                    # If the product of the last dimensions of the shape are equal to the size of the fixed size list array,
                    # we have `num_rows` single element batches (each element is a fixed sized list).
                    # (This should have been already validated by conversion to the arrow_array)
                    batch_length = 1
                else:
                    batch_length = shape[1] if len(shape) > 1 else 1  # type: ignore[redundant-expr,misc]

                num_rows = shape[0] if len(shape) >= 1 else 1  # type: ignore[redundant-expr,misc]
                sizes = batch_length * np.ones(num_rows)
            else:
                # For non-primitive types, default to partitioning each element separately.
                sizes = np.ones(len(arrow_array))

            columns.append(batch.partition(sizes))

        return ComponentColumnList(columns)

    scales: components.HalfSize3DBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.HalfSize3DBatch._converter,  # type: ignore[misc]
    )
    # The scales (standard deviation) along the three axes.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    poss: components.PoseTranslation3DBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.PoseTranslation3DBatch._converter,  # type: ignore[misc]
    )
    # The center position (mean) of the Gaussians.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    rots: components.PoseRotationQuatBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.PoseRotationQuatBatch._converter,  # type: ignore[misc]
    )
    # The rotation for the Gaussians via quaternion.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    colors: components.ColorBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ColorBatch._converter,  # type: ignore[misc]
    )
    # The colors for the Gaussians.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    sh: components.SphericalHarmonicsBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.SphericalHarmonicsBatch._converter,  # type: ignore[misc]
    )
    # Optional spherical harmonics of the Gaussians, up to degree 3.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    labels: components.TextBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.TextBatch._converter,  # type: ignore[misc]
    )
    # Optional text labels for the Gaussians.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    show_labels: components.ShowLabelsBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ShowLabelsBatch._converter,  # type: ignore[misc]
    )
    # Whether the text labels should be shown.
    #
    # If not set, labels will automatically appear when there is exactly one label for this entity
    # or the number of instances on this entity is under a certain threshold.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    class_ids: components.ClassIdBatch | None = field(
        metadata={"component": True},
        default=None,
        converter=components.ClassIdBatch._converter,  # type: ignore[misc]
    )
    # Optional class ID for the Gaussians.
    #
    # The class ID provides colors and labels if not specified explicitly.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    __str__ = Archetype.__str__
    __repr__ = Archetype.__repr__  # type: ignore[assignment]
