# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: rerun/v1alpha1/viewer.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import common_pb2
from . import viewer_pb2


class ViewerControlServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SaveScreenshot(self, stream: 'grpclib.server.Stream[viewer_pb2.SaveScreenshotRequest, viewer_pb2.SaveScreenshotResponse]') -> None:
        pass

    @abc.abstractmethod
    async def SetTimeCursor(self, stream: 'grpclib.server.Stream[viewer_pb2.SetTimeCursorRequest, viewer_pb2.SetTimeCursorResponse]') -> None:
        pass

    @abc.abstractmethod
    async def OpenUrl(self, stream: 'grpclib.server.Stream[viewer_pb2.OpenUrlRequest, viewer_pb2.OpenUrlResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Inspect(self, stream: 'grpclib.server.Stream[viewer_pb2.InspectRequest, viewer_pb2.InspectResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetViewerState(self, stream: 'grpclib.server.Stream[viewer_pb2.GetViewerStateRequest, viewer_pb2.GetViewerStateResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/SaveScreenshot': grpclib.const.Handler(
                self.SaveScreenshot,
                grpclib.const.Cardinality.UNARY_UNARY,
                viewer_pb2.SaveScreenshotRequest,
                viewer_pb2.SaveScreenshotResponse,
            ),
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/SetTimeCursor': grpclib.const.Handler(
                self.SetTimeCursor,
                grpclib.const.Cardinality.UNARY_UNARY,
                viewer_pb2.SetTimeCursorRequest,
                viewer_pb2.SetTimeCursorResponse,
            ),
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/OpenUrl': grpclib.const.Handler(
                self.OpenUrl,
                grpclib.const.Cardinality.UNARY_UNARY,
                viewer_pb2.OpenUrlRequest,
                viewer_pb2.OpenUrlResponse,
            ),
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/Inspect': grpclib.const.Handler(
                self.Inspect,
                grpclib.const.Cardinality.UNARY_UNARY,
                viewer_pb2.InspectRequest,
                viewer_pb2.InspectResponse,
            ),
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/GetViewerState': grpclib.const.Handler(
                self.GetViewerState,
                grpclib.const.Cardinality.UNARY_UNARY,
                viewer_pb2.GetViewerStateRequest,
                viewer_pb2.GetViewerStateResponse,
            ),
        }


class ViewerControlServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SaveScreenshot = grpclib.client.UnaryUnaryMethod(
            channel,
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/SaveScreenshot',
            viewer_pb2.SaveScreenshotRequest,
            viewer_pb2.SaveScreenshotResponse,
        )
        self.SetTimeCursor = grpclib.client.UnaryUnaryMethod(
            channel,
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/SetTimeCursor',
            viewer_pb2.SetTimeCursorRequest,
            viewer_pb2.SetTimeCursorResponse,
        )
        self.OpenUrl = grpclib.client.UnaryUnaryMethod(
            channel,
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/OpenUrl',
            viewer_pb2.OpenUrlRequest,
            viewer_pb2.OpenUrlResponse,
        )
        self.Inspect = grpclib.client.UnaryUnaryMethod(
            channel,
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/Inspect',
            viewer_pb2.InspectRequest,
            viewer_pb2.InspectResponse,
        )
        self.GetViewerState = grpclib.client.UnaryUnaryMethod(
            channel,
            '/rerun.sdk_comms.v1alpha1.ViewerControlService/GetViewerState',
            viewer_pb2.GetViewerStateRequest,
            viewer_pb2.GetViewerStateResponse,
        )
