// DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/cpp/mod.rs
// Based on "crates/store/re_types/definitions/rerun/datatypes/sh.fbs".

#pragma once

#include "../result.hpp"

#include <array>
#include <cstdint>
#include <memory>

namespace arrow {
    class Array;
    class DataType;
    class FixedSizeListBuilder;
} // namespace arrow

namespace rerun::datatypes {
    /// **Datatype**: A spherical harmonics.
    ///
    /// This does not include 0-th degree. It supports up to 3 degrees.
    struct Sh {
        std::array<float, 45> sh;

      public:
        Sh() = default;

        Sh(std::array<float, 45> sh_) : sh(sh_) {}

        Sh& operator=(std::array<float, 45> sh_) {
            sh = sh_;
            return *this;
        }
    };
} // namespace rerun::datatypes

namespace rerun {
    template <typename T>
    struct Loggable;

    /// \private
    template <>
    struct Loggable<datatypes::Sh> {
        static constexpr std::string_view ComponentType = "rerun.datatypes.Sh";

        /// Returns the arrow data type this type corresponds to.
        static const std::shared_ptr<arrow::DataType>& arrow_datatype();

        /// Serializes an array of `rerun::datatypes::Sh` into an arrow array.
        static Result<std::shared_ptr<arrow::Array>> to_arrow(
            const datatypes::Sh* instances, size_t num_instances
        );

        /// Fills an arrow array builder with an array of this type.
        static rerun::Error fill_arrow_array_builder(
            arrow::FixedSizeListBuilder* builder, const datatypes::Sh* elements, size_t num_elements
        );
    };
} // namespace rerun
